config/routes.rb
# See how all your routes lay out with "rake routes"
Fontli::Application.routes.draw do
  # Api controller
  API_ACTIONS = [:log_crash, :stats, :features, :signin, :signup, :signout, :forgot_pass, :reset_pass,
                 :login_check, :check_token, :collections, :collection_search, :follow_collection,
                 :unfollow_collection, :collection_detail, :add_photo_to_collections, :upload_data,
                 :publish_photo, :photo_detail, :update_photo, :delete_photo, :like_photo, :unlike_photo,
                 :flag_photo, :flag_user, :share_photo, :comment_photo, :comments_list, :delete_comment,
                 :add_to_sos, :agree_font, :unagree_font, :fav_font, :unfav_font, :likes_list, :mentions_list,
                 :hash_tag_search, :hash_tag_photos, :hash_tag_feeds, :leaderboard, :popular_photos,
                 :sos_photos, :popular_fonts, :recent_fonts, :font_photos, :font_heat_map, :user_search,
                 :user_profile, :update_profile, :invite_friends, :my_invites, :my_invites_opt, :user_friends,
                 :user_followers, :user_photos, :user_popular_photos, :user_favorites, :user_fonts,
                 :user_fav_fonts, :follow_user, :unfollow_friend, :add_suggestion, :feeds_html,
                 :my_notifications_count, :my_updates, :network_updates, :my_feeds, :feed_detail,
                 :add_workbook, :update_workbook, :list_workbooks, :workbook_photos, :fav_workbook,
                 :unfav_workbook, :recommended_users, :homepage_photos, :update_photo_collections].freeze

  API_ACTIONS.each do |action|
    match "/api/#{action}", to: "api_actions##{action}"
  end
  get "/api/user_detail", to: "api_actions#user_detail"
  get "/api/user_points", to: "api_actions#user_points"

  # Deep Type routes
  resources :deep_type, controller: :deep_types, only: [:destroy] do
    collection do
      post :submission, :status
      get :history, :styles
    end
  end

  # new web routes
  match 'feeds' => 'feeds#index', :as => :feeds
  match 'feeds/show/:id' => 'feeds#show', :as => :show_feed
  match 'socialize-feed/:id' => 'feeds#socialize_feed', :as => :socialize_feed
  match 'follow-user/:id' => 'feeds#follow_user', :as => :follow_user
  match 'unfollow-user/:id' => 'feeds#unfollow_user', :as => :unfollow_user
  match 'sos' => 'feeds#sos', :as => :sos
  match 'feed/:id/fonts' => 'feeds#fonts', :as => :feed_fonts
  match 'fonts/:family_id/:font_id' => 'feeds#show_font', :as => :show_font
  match 'recent-fonts' => 'feeds#recent_fonts', :as => :recent_fonts
  match 'profile/:user_id' => 'feeds#profile', :as => :profile
  match 'popular' => 'feeds#popular', :as => :popular
  match 'my-updates' => 'feeds#my_updates', :as => :my_updates
  match 'network-updates' => 'feeds#network_updates', :as => :network_updates
  match 'search-autocomplete' => 'feeds#search_autocomplete', :as => :search_autocomplete
  match 'search' => 'feeds#search', :as => :search
  match 'font-autocomplete' => 'fonts#font_autocomplete', :as => :font_autocomplete
  match 'font-details/:fontname' => 'fonts#font_details', :as => :font_details
  match 'sub-font-details/:uniqueid' => 'fonts#sub_font_details', :as => :sub_font_details
  match 'tag_font' => 'fonts#tag_font', :as => :tag_font

  # Old Unused routes
  match 'post-feed' => 'feeds#post_feed', :as => :post_feed
  match 'publish-feed/:id' => 'feeds#publish_feed', :as => :publish_feed
  match 'detail_view' => 'feeds#detail_view', :as => :detail_view
  match 'get_mentions_list' => 'feeds#get_mentions_list', :as => :get_mentions_list

  # welcome controller
  root to: 'welcome#index'
  health_check_routes

  match 'keepalive' => 'welcome#keepalive', :as => :keepalive
  match 'login/:platform' => 'welcome#login', :as => :login
  # match 'auth/:platform/callback' => 'welcome#auth_callback', :as => :auth_callback
  get '/unsubscribe/:id', to: 'welcome#unsubscribe', as: 'unsubscribe'
  post '/unsubscribe/:id', to: 'welcome#unsubscribe', as: 'unsubscribe'

  #email controller
  resource :email, controller: :email, only: [] do
    post :bounce
  end
  get 'itunes', to: 'email#itunes', as: 'itunes'

  # admin controller
  get 'admin', to: 'admin#index', as: 'admin'

  resource :admin, controller: :admin, only: [] do
    collection do
      get  :users, :suspended_users, :photos, :flagged_users, :flagged_photos, :sos
      get  :popular_users, :popular_fonts, :users_statistics, :user_stats, :top_contributors
      get  :popular_photos, :send_push_notifications
      post :send_push_notifications, :expire_popular_cache
      put  :suspend_user, :activate_user, :unflag_user, :unflag_photo
      put  :approve_sos, :select_photo, :select_for_header, :update_stat
      delete :delete_user, :delete_photo
    end

    resources :users, only: [:show] do
      member do
        get :add_photo
        post :create_photo
      end
    end
  end

  namespace :admin do
    resources :photos, only: [:edit, :update] do
      collection do
        get :unapproved, :spam
        get :deep_type_requests
      end

      member do
        put :approve
      end
    end

    resources :collections, only: [:index, :create, :edit, :update, :destroy, :show] do
      collection do
        get :fetch_names
      end

      member do
        put :activate, :set_cover_photo
      end
    end
  end

  # Resque Web
  mount Resque::Server.new, at: '/resque'

  # Utils
  constraints host: /(localhost|test\.fontli\.com)/i do
    match 'doc' => 'welcome#api_doc'
  end

  # Permalink - Has to be the last one
  match '*url' => 'feeds#permalink'
end

app/views/admin/_photos.html.erb
<table class='table table-striped table-condensed'>
  <thead>
    <tr>
      <th>&nbsp;</th>
      <th>Image</th>
      <th><%=sortable("caption")%></th>
      <th><%=sortable("likes_count","Likes")%></th>
      <th><%=sortable("comments_count","Comments")%></th>
      <th><%=sortable("fonts_count","Fonts")%></th>
      <th><%=sortable("flags_count","Flags")%></th>
      <th>Username</th>
      <th>User Device OS</th>
      <th><%=sortable("created_at","Created")%></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% count = ( (params[:page] || 1).to_i - 1) * 25 %>
    <% photos.each_with_index do |f, i| %>
    <tr id='foto_<%= f.id.to_s %>'>
      <td><%= count += 1 %></td>
      <td>
        <a href='/<%= f.perma %>' target='_new'>
          <img src='<%= f.url_medium %>' />
        </a>
      </td>
      <td><%= f.caption %></td>
      <td><%= f.likes_count %></td>
      <td><%= f.comments_count %></td>
      <td><%= f.fonts_count %></td>
      <td><%= f.flags_count %></td>
      <td><%= f.user.username rescue 'User Flagged' %></td>
      <td><%= f.user.try(:os) %></td>
      <td><%= f.created_dt %></td>
      <td class='actions_link'>
        <% if params[:req] == 'true' %>
          <%= link_to('Approve SoS', approve_sos_admin_path(photo_id: f.id), remote: true, method: :put ) %>
        <% end %>
        <% if @unflag_photo %>
          <%= link_to('Unflag', unflag_photo_admin_path(id: f.id), remote: true, method: :put, confirm: 'Are you sure you want to unflag this photo?') %>
        <% end %>
        <%= link_to 'Edit', edit_admin_photo_path(f), remote: true if f.user.try(:is_editable?) %>
        <%= link_to('Delete', delete_photo_admin_path(id: f.id), remote: true, method: :delete, confirm: 'Are you sure you want to delete this photo? This cannot be undone!') %>
        <% if @select_photo && !f.show_in_homepage? %>
          <%= link_to('Select', select_photo_admin_path(id: f.id), remote: true, method: :put, title: 'Select for homepage') %>
        <% end %>
        <% if @unselect_photo && f.show_in_homepage? %>
          <%= link_to('Unselect', select_photo_admin_path(id: f.id, select: false), remote: true, method: :put) %>
        <% end %>
        <% if defined?(cover_photo) && f.id.to_s != @collection.try(:cover_photo_id) %>
          <%= link_to('Cover Photo', set_cover_photo_admin_collection_path(photo_id: f.id), method: :put, class: 'cover_photo_link') %>
        <% end %>
        <% if defined?(approve_photo)%>
          <%= link_to('Approve', approve_admin_photo_path(f.id), method: :put, remote: true) %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<div class="modal fade" id="photo_modal" role="dialog" data-backdrop="static" data-keyboard="false"></div>

app/views/admin/_popular_header.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'jquery-ui' %>
  <style type="text/css">
    .custom-state-active { background: #eee; }
    #to_approve, #approved { float:left; min-height:20em; width:480px; border:2px solid #eee; margin:20px 0 0 30px; }
    #to_approve img, #approved img { padding:2px; cursor:move; }
  </style>
<% end %>
<% content_for :custom_js do %>
  $('.draggable').draggable({
    revert: 'invalid',
    containment: 'document',
    helper: 'clone'
  });
  $("#approved").droppable({
    accept: "#to_approve img",
    activeClass: 'ui-state-highlight',
    drop: function(event, ui) {
      reportStatus(ui.draggable, true);
    }
  });
  $("#to_approve").droppable({
    accept: "#approved img",
    activeClass: 'custom-state-active',
    drop: function(event, ui) {
      reportStatus(ui.draggable, false);
    }
  });
  function reportStatus($item, status) {
    var targetElem = status ? $('#approved') : $('#to_approve');
    var id = $item.attr('data-id');
    var modal = $item.attr('data-modal') || 'User';
    var url = '/admin/select_for_header';
    $.ajax({
      url: url,
      type: 'put',
      data: {id: id, modal: modal, status: status},
      success: function(data) { $item.appendTo(targetElem); },
      error: function(data) { alert('failed'); }
    });
  }
<% end %>

app/views/admin/_top_nav.html.erb
<ul class="nav">
  <li class="<%=  active_class('index') %>">
    <%= link_to 'Home', admin_path %>
  </li>
  <li class="dropdown <%= active_class('users', 'suspended_users', 'users_statistics', 'top_contributors') %>" id="menu1">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">Users <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'All', users_admin_path %></li>
      <li><%= link_to 'Suspended', suspended_users_admin_path %></li>
      <li><%= link_to 'Statistics', users_statistics_admin_path %></li>
      <li><%= link_to 'Top Contributors', top_contributors_admin_path %></li>
    </ul>
  </li>
  <li class="dropdown <%= active_class('photos') %>" id="menu2">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu2">Photos <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'All', photos_admin_path %></li>
      <li><%= link_to 'For homepage', photos_admin_path(home: true) %></li>
      <li><%= link_to 'Unapproved', unapproved_admin_photos_path %></li>
      <li><%= link_to 'Spam', spam_admin_photos_path %></li>
      <li><%= link_to 'DeepTypeRequests', deep_type_requests_admin_photos_path %></li>
    </ul>
  </li>
  <li class="dropdown <%= active_class('collections') %>" id="menu6">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu6">Collections <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'View List', admin_collections_path %></li>
    </ul>
  </li>
  <li class="dropdown <%= active_class('sos') %>" id="menu3">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu3">SoS <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Approved', sos_admin_path %></li>
      <li><%= link_to 'Requested', sos_admin_path(req: true) %></li>
    </ul>
  </li>
  <li class="dropdown <%= active_class('popular_users', 'popular_photos', 'popular_fonts') %>" id="menu4">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu4">Popular Content <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Users', popular_users_admin_path %></li>
      <li><%= link_to 'Photos', popular_photos_admin_path %></li>
      <li><%= link_to 'Fonts', popular_fonts_admin_path %></li>
    </ul>
  </li>
  <li class="dropdown <%= active_class('flagged_users', 'flagged_photos') %>" id="menu5">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#menu5">Flagged Content <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <li><%= link_to 'Users', flagged_users_admin_path  %></li>
      <li><%= link_to 'Photos', flagged_photos_admin_path %></li>
    </ul>
  </li>
</ul>

app/views/admin/approve_sos.js.erb
<% if @res %>
  $('#foto_<%= params[:photo_id] %>').html('<td colspan=3>Approved.</td>')
<% else %>
  alert('Couldn\'t Approve!');
<% end %>

app/views/admin/index.html.erb
<% content_for :custom_js do %>
  $('#update_stat_link').live('click', function(e) {
    $(this).hide();
    $('#update_stat_cancel').show();
    $('#update_stat_form .submit').show();
    $('#status').html('');
    $('#update_stat_form').slideDown();
  });

  $('#update_stat_form').live('ajax:before', function(e) {
    $('#status').html('Updating...');
    $('#update_stat_cancel').hide();
    $('#update_stat_form .submit').hide();
  });

  $('#update_stat_form').live('ajax:success', function(data, status, xhr) {
    $('#app_version').html(data['app_version']);
    $('#app_version').fadeIn();
    $('#status').html('Updated.');
    $('#update_stat_form').hide();
  });

  $('#update_stat_cancel').live('click', function(e) {
    $('#update_stat_form').hide();
    $('#update_stat_link').show();
  });
<% end %>

<%= render 'shared/flash_notices' %>

<h3>App Stats</h3>
<ul>
  <li>Total Users: <%= link_to @admin_presenter.users_count, users_admin_path %></li>
  <li>New users since <%= Time.now.beginning_of_month %>: <%= @admin_presenter.new_users_count %></li>
  <li>New users in past 30 days: <%= @admin_presenter.users_in_past_30_days %></li>
  <li>Users with atleast one photo: <%= @admin_presenter.users_with_photos %></li>
  <li>Users with just one post: <%= @admin_presenter.users_with_one_photo %></li>
  <li>Number of users currently active: <%= @admin_presenter.online_users_count %></li> 
  <li>Users sharing to other platforms: <%= @admin_presenter.users_sharing_to_other_platforms %></li>

  <li>Total Photos: <%= link_to @admin_presenter.photos_count, photos_admin_path %></li>
  <li>Homepage Photos: <%= link_to @admin_presenter.homepage_photos_count, photos_admin_path(home: true) %></li>
  <li>Total number of SOS: <%= @admin_presenter.sos_count %></li>
  <li>SOS with responses: <%= @admin_presenter.sos_with_responses_count %></li>
  <li>Number of posts shared to other platforms: <%= @admin_presenter.shared_post_count %></li>

  <li>Most photographed location: <%= @admin_presenter.most_photographed_location %></li>
  <li>Login medium: <%= @admin_presenter.login_medium %></li>
  <li>
    App Version: <span id="app_version"><%= @admin_presenter.current_stat.app_version %></span>&nbsp;&nbsp;
    <%= link_to 'Change', 'javascript:void(0);', :id => 'update_stat_link' %>
    <%= form_tag update_stat_admin_path, id: 'update_stat_form', method: :put, class: 'form-inline', style: 'display:none; margin-top:10px;' do %>
      <input class="span1" name="version" type="text" size="10" value='<%= @admin_presenter.current_stat.app_version %>' />
      <input type="submit" class="submit btn btn-primary" value="Update" />
      <%= link_to 'Cancel', 'javascript:void(0);', :id => 'update_stat_cancel' %>
    <% end %>
    <span id="status">&nbsp;</span>
  </li>
</ul><br/>

<h3>Backend Stats</h3>
<ul>
  <% @admin_presenter.current_stat.misc_attrs.each do |k, v| %>
    <li><%= k.humanize %>: <%= link_to v, 'javascript:;' %></li>
  <% end %>
</ul><br/>

<h3>Utilities</h3>
<ul>
  <li><%= link_to 'Send Push notifications', send_push_notifications_admin_path %> to all users.</li>
</ul>

app/views/admin/photos.html.erb
<h3><%= @title || 'Photos' %> <span class="badge badge-info"><%= @fotos.total_count %></span> </h3>

<form class="well form-search">
  <% ['req', 'home', 'user_id'].each do |p| %>
    <% if params[p.to_sym].present? %>
      <input type="hidden" name='<%= p %>' value='<%= params[p.to_sym] %>' /> 
    <% end %>
  <% end %>
  <input type="text" name='search' value='<%= params[:search]%>' class="input-medium search-query">
  <button type="submit" class="btn">Search</button>
</form>

<%= render 'shared/flash_notices' %>
<%= render 'photos', photos: @fotos %>
<%= paginate @fotos %>

app/views/admin/popular_photos.html.erb
<%= render 'popular_header' %>

<% photos_selected = @photos.select(&:show_in_header) %>
<% photos_to_select = @photos - photos_selected %>

<div class='span10'>
  <h3 class='pull-left'>
    Popular <%= @font_page ? 'Fonts' : 'Photos' %>
    <span class='label label-info'>Cached for <%= @font_page ? 48 : 24 %> hours</span>
  </h3>
  <%= link_to('Expire cache now', expire_popular_cache_admin_path, method: :post, class: 'btn btn-primary pull-right', title: 'Please run this once you are completely done curating Users, Photos and Fonts.', rel: 'tooltip') %>
  <div style='clear:both;'>&nbsp;</div>
</div>

<div id="to_approve" class="ui-widget ui-helper-clearfix">
  <h5>Content to Approve</h5>
  <% photos_to_select.each do |p| %>
    <img src='<%= p.url_thumb %>' data-id='<%= p.id.to_s %>' data-modal='Photo' title="<%= p.caption %>" class='draggable' />
  <% end %>
</div>

<div id="approved" class="ui-widget ui-state-default">
  <h5>Approved Content</h5>
  <% photos_selected.each do |p| %>
    <img src='<%= p.url_thumb %>' data-id='<%= p.id.to_s %>' data-modal='Photo' title="<%= p.caption %>" class='draggable' />
  <% end %>
  &nbsp;
</div>
<div style="clear:left;">&nbsp;</div>

app/views/admin/popular_users.html.erb
<%= render 'popular_header' %>

<% users_selected = @users.select(&:show_in_header) %>
<% users_to_select = @users - users_selected %>

<div class='span10'>
  <h3 class='pull-left'>Popular Users <span class='label label-info'>Cached for 24 hours</span></h3>
  <%= link_to('Expire cache now', expire_popular_cache_admin_path, method: :post, class: 'btn btn-primary pull-right', title: 'Please run this once you are completely done curating Users, Photos and Fonts.', rel: 'tooltip') %>
  <div style='clear:both;'>&nbsp;</div>
</div>

<div id="to_approve" class="ui-widget ui-helper-clearfix">
  <h5>Content to Approve</h5>
  <% users_to_select.each do |u| %>
    <img src='<%= u.url_thumb %>' data-id='<%= u.id.to_s %>' title="<%= u.username %>" class='draggable' />
  <% end %>
</div>

<div id="approved" class="ui-widget ui-state-default">
  <h5>Approved Content</h5>
  <% users_selected.each do |u| %>
    <img src='<%= u.url_thumb %>' data-id='<%= u.id.to_s %>' title="<%= u.username %>" class='draggable' />
  <% end %>
  &nbsp;
</div>
<div style="clear:left;">&nbsp;</div>

app/views/admin/select_photo.js.erb
<% if @res %>
  <% resp_text = params[:select].to_s == 'false' ? 'Unselected' : 'Selected' %>
  $('#foto_<%= params[:id] %> td:last strong').text('<%= resp_text %>');
<% else %>
  alert('Request Failed!');
<% end %>

app/views/admin/send_push_notifications.html.erb
<h3>Send push notification</h3>
<div>
  <span style="font-weight:bold;color:red">Use with caution:</span>
  This is a DB and memory intensive process and might block the live instance.
</div><br/>

<%= render 'shared/flash_notices' %>

<%= form_tag send_push_notifications_admin_path, method: 'post', class: 'form' do %>
  <div class="control-group">
    <label>Message (120 chars max):</label>
    <input type="text" name="message" class="span8" />
  </div>

  <input type="submit" class="btn btn-primary" value="Send" />
<% end %>

app/views/admin/top_contributors.html.erb
<h3>Top Contributors
  <span class="badge badge-info"><%= @top_contributors.total_count %></span>
  <%= link_to "Export as CSV", url_for(params.merge(format: :csv)), class: 'btn pull-right' %>
</h3>

<form class="well form-search">
  <input type="text" name='search' value='<%= params[:search]%>' class="input-medium search-query">
  <button type="submit" class="btn">Search</button>
</form>

<%= render 'shared/flash_notices' %>

<table class='table table-striped table-condensed'>
  <thead>
    <tr>
      <th>&nbsp;</th>
      <th>Avatar</th>
      <th><%=sortable("username")%></th>
      <th><%=sortable("full_name","Full Name")%></th>
      <th><%=sortable("email")%></th>
      <th><%=sortable("photos_count","Photos")%></th>
      <th><%=sortable("follows_count","Follows")%></th>
      <th><%=sortable("platform","Platform")%></th>
      <th><%=sortable("user_flags_count", "Flag Count")%></th>
      <th><%=sortable("created_at","Created")%></th>
      <th>Last Activity</th>
    </tr>
  </thead>
  <tbody>
    <% count = ((params[:page] || 1).to_i - 1) * 25 %>
    <% @top_contributors.each_with_index do |u, i| %>
    <% fotos_cnt = u.photos_count %>
    <tr id='usr_<%= u.id.to_s %>'>
      <td><%= count += 1 %></td>
      <td><img src='<%= u.url_thumb %>' /></td>
      <td><%= u.username %></td>
      <td><%= valid_string(u.full_name) %></td>
      <td><%= u.email %></td>
      <% if fotos_cnt > 0 %>
        <td><%= link_to fotos_cnt, photos_admin_path(user_id: u.id) %></td>
      <% else %>
        <td><%= fotos_cnt %></td>
      <% end %>
      <td><%= u.follows_count %></td>
      <td><%= u.platform %></td>
      <td><%= u.user_flags_count %></td>
      <td><%= u.created_dt %></td>
      <td><%= last_activity(u) %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @top_contributors %>

app/views/admin/unflag_photo.js.erb
<% if @res %>
  $('#foto_<%= params[:id] %>').html('<td colspan=3>Unflagged.</td>')
<% else %>
  alert('Couldn\'t Unflag!');
<% end %>

app/views/admin/users.html.erb
<h3><%= @title || 'Users' %> <span class="badge badge-info"><%= @users.total_count %></span> </h3>

<form class="well form-search">
  <input type="text" name='search' value='<%= params[:search]%>' class="input-medium search-query">
  <button type="submit" class="btn">Search</button>
</form>

<%= render 'shared/flash_notices' %>

<table class='table table-striped table-condensed'>
  <thead>
    <tr>
      <th>&nbsp;</th>
      <th>Avatar</th>
      <th><%=sortable("username")%></th>
      <th><%=sortable("full_name","Full Name")%></th>
      <th><%=sortable("email")%></th>
      <th><%=sortable("photos_count","Photos")%></th>
      <th><%=sortable("follows_count","Follows")%></th>
      <th>Platform</th>
      <th>OS</th>
      <th><%=sortable("user_flags_count", "Flag Count")%></th>
      <th><%=sortable("points")%></th>
      <th><%=sortable("created_at","Created")%></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% count = ((params[:page] || 1).to_i - 1) * 25 %>
    <% @users.each_with_index do |u, i| %>
    <% fotos_cnt = u.photos_count %>
    <tr id='usr_<%= u.id.to_s %>'>
      <td><%= count += 1 %></td>
      <td><img src='<%= u.url_thumb %>' /></td>
      <td><%= u.username %></td>
      <td><%= valid_string(u.full_name) %></td>
      <td><%= u.email %></td>
      <% if fotos_cnt > 0 %>
        <td><%= link_to fotos_cnt, photos_admin_path(user_id: u.id) %></td>
      <% else %>
        <td><%= fotos_cnt %></td>
      <% end %>
      <td><%= u.follows_count %></td>
      <td><%= u.platform %></td>
      <td><%= u.os %></td>
      <td><%= u.user_flags_count %></td>
      <td><%= u.points %></td>
      <td><%= u.created_dt %></td>
      <td class='actions_link'>
        <%= link_to 'Show', admin_user_path(u) %>
        <% if @suspend_user %>
          <%= link_to('Suspend', suspend_user_admin_path(id: u.id), method: 'put') %>
        <% end %>
        <% if @unflag_user %>
          <%= link_to('UnFlag', unflag_user_admin_path(id: u.id), method: 'put') %>
        <% end %>
        <% if @activate_user %>
          <%= link_to('Activate', activate_user_admin_path(id: u.id), method: 'put') %>
        <% end %>
        <% if @delete_user %>
          <%= link_to('Delete', delete_user_admin_path(id: u.id), method: :delete, confirm: "Are you sure you want to delete #{u.username}? This cannot be undone!") %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @users %>

app/views/admin/users_statistics.html.erb
<div id="users_statistics" style="min-width: 310px; height: 400px; margin: 0 auto"></div>