config/routes.rb
# See how all your routes lay out with "rake routes"
Fontli::Application.routes.draw do
  # Api controller
  API_ACTIONS = [:log_crash, :stats, :features, :signin, :signup, :signout, :forgot_pass, :reset_pass,
                 :login_check, :check_token, :collections, :collection_search, :follow_collection,
                 :unfollow_collection, :collection_detail, :add_photo_to_collections, :upload_data,
                 :publish_photo, :photo_detail, :update_photo, :delete_photo, :like_photo, :unlike_photo,
                 :flag_photo, :flag_user, :share_photo, :comment_photo, :comments_list, :delete_comment,
                 :add_to_sos, :agree_font, :unagree_font, :fav_font, :unfav_font, :likes_list, :mentions_list,
                 :hash_tag_search, :hash_tag_photos, :hash_tag_feeds, :leaderboard, :popular_photos,
                 :sos_photos, :popular_fonts, :recent_fonts, :font_photos, :font_heat_map, :user_search,
                 :user_profile, :update_profile, :invite_friends, :my_invites, :my_invites_opt, :user_friends,
                 :user_followers, :user_photos, :user_popular_photos, :user_favorites, :user_fonts,
                 :user_fav_fonts, :follow_user, :unfollow_friend, :add_suggestion, :feeds_html,
                 :my_notifications_count, :my_updates, :network_updates, :my_feeds, :feed_detail,
                 :add_workbook, :update_workbook, :list_workbooks, :workbook_photos, :fav_workbook,
                 :unfav_workbook, :recommended_users, :homepage_photos, :update_photo_collections].freeze

  API_ACTIONS.each do |action|
    match "/api/#{action}", to: "api_actions##{action}"
  end
  get "/api/user_detail", to: "api_actions#user_detail"
  get "/api/user_points", to: "api_actions#user_points"

  # Deep Type routes
  resources :deep_type, controller: :deep_types, only: [:destroy] do
    collection do
      post :submission, :status
      get :history, :styles
    end
  end

  # new web routes
  match 'feeds' => 'feeds#index', :as => :feeds
  match 'feeds/show/:id' => 'feeds#show', :as => :show_feed
  match 'socialize-feed/:id' => 'feeds#socialize_feed', :as => :socialize_feed
  match 'follow-user/:id' => 'feeds#follow_user', :as => :follow_user
  match 'unfollow-user/:id' => 'feeds#unfollow_user', :as => :unfollow_user
  match 'sos' => 'feeds#sos', :as => :sos
  match 'feed/:id/fonts' => 'feeds#fonts', :as => :feed_fonts
  match 'fonts/:family_id/:font_id' => 'feeds#show_font', :as => :show_font
  match 'recent-fonts' => 'feeds#recent_fonts', :as => :recent_fonts
  match 'profile/:user_id' => 'feeds#profile', :as => :profile
  match 'popular' => 'feeds#popular', :as => :popular
  match 'my-updates' => 'feeds#my_updates', :as => :my_updates
  match 'network-updates' => 'feeds#network_updates', :as => :network_updates
  match 'search-autocomplete' => 'feeds#search_autocomplete', :as => :search_autocomplete
  match 'search' => 'feeds#search', :as => :search
  match 'font-autocomplete' => 'fonts#font_autocomplete', :as => :font_autocomplete
  match 'font-details/:fontname' => 'fonts#font_details', :as => :font_details
  match 'sub-font-details/:uniqueid' => 'fonts#sub_font_details', :as => :sub_font_details
  match 'tag_font' => 'fonts#tag_font', :as => :tag_font

  # Old Unused routes
  match 'post-feed' => 'feeds#post_feed', :as => :post_feed
  match 'publish-feed/:id' => 'feeds#publish_feed', :as => :publish_feed
  match 'detail_view' => 'feeds#detail_view', :as => :detail_view
  match 'get_mentions_list' => 'feeds#get_mentions_list', :as => :get_mentions_list

  # welcome controller
  root to: 'welcome#index'
  health_check_routes

  match 'keepalive' => 'welcome#keepalive', :as => :keepalive
  match 'login/:platform' => 'welcome#login', :as => :login
  # match 'auth/:platform/callback' => 'welcome#auth_callback', :as => :auth_callback
  get '/unsubscribe/:id', to: 'welcome#unsubscribe', as: 'unsubscribe'
  post '/unsubscribe/:id', to: 'welcome#unsubscribe', as: 'unsubscribe'

  #email controller
  resource :email, controller: :email, only: [] do
    post :bounce
  end
  get 'itunes', to: 'email#itunes', as: 'itunes'

  # admin controller
  get 'admin', to: 'admin#index', as: 'admin'

  resource :admin, controller: :admin, only: [] do
    collection do
      get  :users, :suspended_users, :photos, :flagged_users, :flagged_photos, :sos
      get  :popular_users, :popular_fonts, :users_statistics, :user_stats, :top_contributors
      get  :popular_photos, :send_push_notifications
      post :send_push_notifications, :expire_popular_cache
      put  :suspend_user, :activate_user, :unflag_user, :unflag_photo
      put  :approve_sos, :select_photo, :select_for_header, :update_stat
      delete :delete_user, :delete_photo
    end

    resources :users, only: [:show] do
      member do
        get :add_photo
        post :create_photo
      end
    end
  end

  namespace :admin do
    resources :photos, only: [:edit, :update] do
      collection do
        get :unapproved, :spam
        get :deep_type_requests
      end

      member do
        put :approve
      end
    end

    resources :collections, only: [:index, :create, :edit, :update, :destroy, :show] do
      collection do
        get :fetch_names
      end

      member do
        put :activate, :set_cover_photo
      end
    end
  end

  # Resque Web
  mount Resque::Server.new, at: '/resque'

  # Utils
  constraints host: /(localhost|test\.fontli\.com)/i do
    match 'doc' => 'welcome#api_doc'
  end

  # Permalink - Has to be the last one
  match '*url' => 'feeds#permalink'
end

app/controllers/welcome_controller.rb
require 'auth_client'
require 'storify_client'

class WelcomeController < ApplicationController
  include AuthClient
  skip_before_filter :login_required
  skip_before_filter :set_current_controller, :only => [:keepalive]

  layout :select_layout

  def keepalive
    render :text => 'Success'
  end

  def index
    redirect_to(feeds_url) && return if logged_in?
    @story   = StorifyStory.random_story
    @popular = Photo.for_homepage.only(:id,:data_filename).to_a
    @homepage, @meta_title = true, 'Home'
  end

  def login
    return if request.get?
    self.send format('%s_login', params[:platform])
  end

  def api_doc
    render 'api_doc', :layout => false
  end

  def unsubscribe
    @user = User.where(id: params[:id]).last
    @user.update_attribute(:unsubscribed, true)
    return if request.get?
    @user.update_attribute(:unsubscription_reason, params[:reason_id]) if params[:reason_id].present?
    UnsubscriptionReason.create(user_id: @user.id, description: params[:description]) if params[:description].present?
    redirect_to root_path
  end

  private

  def default_login
    uname, pass = [params[:username], params[:password]]
    if uname.blank? || pass.blank?
      flash.now[:alert] = 'Username or Password is blank!'
      return false
    end
    u = User.login uname, pass
    unless u.nil?
      session[:user_id] = u.id
      redirect_to feeds_url
    else
      flash.now[:alert] = 'Invalid username or password!'
    end
  end

  def select_layout
    if [:login, :unsubscribe].include?(params[:action].to_sym)
      'plain'
    else
      'application'
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_signin.html.erb
<div class="signin" >
  <div class="innershade">
    <a class="img-cross">
      <img src="<%= asset_path('cross-signin.png') %>" width="22" height="22" alt="" title="" />
    </a>
    <div class="image-container">
      <img src="<%= asset_path('fontli-logo.png') %>" width="150" height="85" alt="" title="" />
      <h2 class="signin">Sign in</h2>
    </div>

    <div class="signin-panel">
      <div class="credential-panel">
      <%= form_tag login_path(:default) do %>
        <input type="text" name="username" placeholder="Username or Email Id" class="credential" /><br/>
        <input type="password" name="password" placeholder="Password" class="credential" /><br />
        <button>Sign in</button>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/api_doc.html.erb
<% require 'api_helper' %>

<!DOCTYPE html>
<html>
  <head>
    <title>Fontli: API Doc</title>
    <style type="text/css">
      p { margin:10px 0; padding:0; }
      .note { font-weight: bold; color: gray; }
      #methods { padding: 10px; border-top: 1px solid black; }
      #methods .name { font-weight: bold; }
      #methods .collection { color: gray; margin-left: 20px; }
      #methods .returns { padding-bottom: 10px; border-bottom: 1px dotted gray; }
    </style>
  </head>

  <body>
    <h3>API Documentation</h3>
    <span>Last updated on <%= '23/09/2016'.to_date.strftime('%B %d,%Y') %></span>
    <p>All API methods(except <code>signin, signup, login check</code>) requires <code>auth_token</code> param to identify the user session. User-session(and hence the <code>auth_token</code>) expires in 4weeks by default and user has to be signed in again upon expiry.</p>
    <p><span class="note">Note:</span> For FB/Twitter users, there's no concept of sessions. The state is controlled using encrypted <code>extuid_token</code> - derived from <code>auth_token</code>.</p>
    <p>All API response will include: </p>
    <pre>
      1. response: Actual response of the action as defined below, specific to action, can be empty.
      2. status:   Will be "Success" on success and "Failure" on failure.
      3. errors:   Comma seperated string of errors, if status is "Failure", can be empty on "Success".
    </pre>

    <div id="methods">
      <% ApiHelper::SIGNATURE_MAP.each do |k, v| %>
        <p class='name'>/api/<%= k.to_s %></p>
        <p class='accepts'>Accepts: <%= ApiHelper.accepts_label_for(k) %></p>
        <div class='collection'>
          <%= ApiHelper.collection_label_for(k) %>
        </div>
        <p class='returns'>Returns: <%= ApiHelper.returns_label_for(k) %></p>
      <% end %>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<% content_for :pre_content do %>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

  <div id='qr_pop'>
    <%= render 'shared/qr_popup' %>
  </div>
<% end %>
<% content_for :custom_js do %>
  photoIds = <%= sanitize @popular.collect(&:id).to_json %>;
<% end %>

<section id="secondaryHeader">
<div class="wrapper">
  <blockquote>
    <p>
      <%= @story.text %> <br />
      <cite><%= @story.name %></cite>
      <a class='storify-link' href="http://storify.com" target='blank'>Powered by Storify</a>
    </p>
  </blockquote>
  <aside>
    <button id="join_fontli" href="<%= popular_path(:type => 'post') %>">
      <span class='join-cta'>
        Discover
        <span><%= number_with_delimiter(User.count) %></span>
        typoholics
      </span>
    </button>
    <div class="share">
      <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://www.fontli.com" data-text="@fontli, Fontli- discover and share pure type love!"></a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      <div class="fb-like" data-href="http://www.fontli.com/" data-send="false" data-layout="button_count" data-show-faces="false"></div>
    </div>
  </aside>
</div>
</section>

<section id="banner" class="big">
<div class="wrap slide-banner">
  <div id="slider1" class="slider">
    <ul>
      <% @popular.each_with_index do |p, i| %>
      <li data-id='<%= p.id %>' href='<%= show_feed_path(p) %>' rel='popitup'>
        <div style='background: none no-repeat; width:305px;height:305px;'>
          <div class="img-shadow"></div>
          <% if(i < 9) # load only the first 10 images upfront %>
            <img src="<%= p.url(:medium) %>" style="width:305px;height:305px;" />
          <% else # rest are loaded later %>
            <img src="<%= render('/shared/black_img_data') %>" xsrc="<%= p.url(:medium) %>" style="width:305px;height:305px;" />
          <% end %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
  <%= render 'shared/controls' %>
</div>
</section>

<!-- preload images for popup -->
<% @popular.each do |p| %>
  <img xsrc="<%= p.url(:large) %>" class='hidden-img' style="display:none;" />
<% end %>

app/views/welcome/login.html.erb
<%= render 'signin' %>

app/views/welcome/login.js.erb
hideAjaxLoader();
$('#popup_container').html('<%= escape_javascript(render('welcome/signin')) %>');
$('#popup_container').show();

app/views/welcome/unsubscribe.html.erb
<div class='unsubscribe-container'>
  <div class='unsubscribe'>
    <h3>Unsubscribe Successful</h3>
    <p>You have been unsubscribed from Fontli.</p>
    <p>If you have a moment, please let us know why you unsubscribed:</p>
    <%= form_tag unsubscribe_path, method: 'post' do %>
      <% UnsubscriptionReason.default.each do |reason| %>
        <%= radio_button_tag :reason_id, reason.id, false %>
        <%= label_tag :reason_id, reason.description %><br />
      <% end %>
      <%= radio_button_tag :reason_id, false, false %>
      <%= label_tag :reason_id, 'Other (fill in reason below)' %><br />
      <%= text_field_tag :description, '', class: 'hide' %>
      <%= submit_tag 'Submit' %>
    <% end %>
    <%= link_to '« Return to our website', root_path %>
  </div>
</div>